spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketsystem
    username: postgres
    password: ar4ebar4e
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
